feat: Rating component
swordev/suid pull request #299
Opened 2024-08-03 02:35 UTC by Phinome

1. added rating component
2. fixed cli helper message
3. added some necessary files

please help CR, thx.

feel free to me if you have any question.

Best Regards,

Phinome

2024-08-19 03:44 UTC, Phinome commented
no body care?

2024-08-20 18:32 UTC, juanrgm requested changes

2024-08-20 18:32 UTC, juanrgm commented on packages/material/src/Rating/Rating.tsx
> +  const isFilled = props.highlightSelectedOnly
This code is not reactive.

2024-08-20 18:32 UTC, juanrgm commented on packages/material/src/Rating/Rating.tsx
> +    return <span {...props.labelProps}>{container}</span>;
Notn reactive.

2024-08-20 18:32 UTC, juanrgm commented on packages/material/src/Rating/Rating.tsx
> +  const valueRounded = roundValueToPrecision(
Non reactive.

2025-01-16 02:59 UTC, Phinome commented
Thank you for your help; I have resolved all the issues.

2025-04-17 19:00 UTC, merged